# ===========================================
# Production Docker Compose for Coolify
# ===========================================

version: '3.8'

services:
  optia-bff:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "9090:9090"  # Metrics port
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      # Coolify labels for automatic deployment
      - "coolify.managed=true"
      - "coolify.version=1.0.0"
      - "coolify.type=application"
    networks:
      - optia-network

networks:
  optia-network:
    external: true
    name: coolify
