openapi: 3.1.0
info:
  title: Optica BFF API
  version: 0.1.0
  description: Generated minimal spec (partial) for core routes.
servers:
  - url: https://api.example.com
paths:
  /healthz:
    get:
      summary: Liveness probe
      responses:
        '200':
          description: OK
  /ready:
    get:
      summary: Readiness probe
      responses:
        '200': { description: Ready }
        '503': { description: Degraded }
  /products:
    get:
      summary: List products
      parameters:
        - in: query
          name: page
          schema: { type: integer, minimum: 1 }
        - in: query
          name: per_page
          schema: { type: integer, minimum: 1, maximum: 100 }
      responses:
        '200': { description: Product list }
  /products/{id}:
    get:
      summary: Get product detail
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        '200': { description: Product }
        '404': { description: Not found }
  /auth/login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string }
                password: { type: string }
      responses:
        '200': { description: Auth success }
        '401': { description: Invalid credentials }
  /auth/refresh:
    post:
      summary: Refresh access token
      responses:
        '200': { description: New tokens }
        '401': { description: Invalid or revoked }
  /admin/cache/invalidate:
    post:
      summary: Invalidate cache pattern
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                pattern: { type: string }
      responses:
        '200': { description: Invalidation success }
        '400': { description: Invalid request }
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
