name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install deps
        run: npm ci
      - name: Generate Prisma client
        run: npm run postinstall
      - name: Build
        run: npm run build
      - name: Prisma validate
        run: npx prisma validate
      - name: Type check (tsc --noEmit)
        run: npx tsc --noEmit
